export const salaryOptions = [
  { value: "20k", label: "20k" },
  { value: "30k-45k", label: "30k-45k" },
  { value: "50k-70k", label: "50k-70k" },
  { value: "75k-90k", label: "75k-90k" },
  { value: "90k-100k", label: "90k-100k" },
  { value: "100k+", label: "100k+" },
];
export const typeOptions = [
  { value: "Full-time", label: "Full-Time" },
  { value: "Part-time", label: "Part-Time" },
  { value: "Internship", label: "Internship" },
];

export const positions = [
  { value: "Software Engineer", label: "Software Engineer" },
  { value: "Frontend Developer", label: "Frontend Developer" },
  { value: "Backend Developer", label: "Backend Developer" },
  { value: "Fullstack Developer", label: "Fullstack Developer" },
  { value: "Mobile Developer", label: "Mobile Developer" },
  { value: "Game Developer", label: "Game Developer" },
  { value: "Web Developer", label: "Web Developer" },
  { value: "Database Administrator", label: "Database Administrator" },
  { value: "Data Scientist", label: "Data Scientist" },
  { value: "DevOps Engineer", label: "DevOps Engineer" },
  { value: "Cloud Engineer", label: "Cloud Engineer" },
  { value: "Machine Learning Engineer", label: "Machine Learning Engineer" },
  {
    value: "Artificial Intelligence Engineer",
    label: "Artificial Intelligence Engineer",
  },
  { value: "Software Architect", label: "Software Architect" },
  { value: "UI/UX Designer", label: "UI/UX Designer" },
  { value: "Product Manager", label: "Product Manager" },
  { value: "IT Manager", label: "IT Manager" },
  { value: "Project Manager", label: "Project Manager" },
  { value: "Quality Assurance Engineer", label: "Quality Assurance Engineer" },
  { value: "Technical Writer", label: "Technical Writer" },
  { value: "System Administrator", label: "System Administrator" },
  { value: "Network Administrator", label: "Network Administrator" },
  { value: "Security Engineer", label: "Security Engineer" },
  { value: "Embedded Systems Engineer", label: "Embedded Systems Engineer" },
  { value: "Firmware Engineer", label: "Firmware Engineer" },
  { value: "Java Developer", label: "Java Developer" },
  { value: "Python Developer", label: "Python Developer" },
  { value: "Ruby Developer", label: "Ruby Developer" },
  { value: "JavaScript Developer", label: "JavaScript Developer" },
  { value: "C++ Developer", label: "C++ Developer" },
  { value: "C# Developer", label: "C# Developer" },
  { value: "PHP Developer", label: "PHP Developer" },
  { value: "Perl Developer", label: "Perl Developer" },
  { value: "Swift Developer", label: "Swift Developer" },
  { value: "Kotlin Developer", label: "Kotlin Developer" },
  { value: "Objective-C Developer", label: "Objective-C Developer" },
  { value: "Scala Developer", label: "Scala Developer" },
  { value: "Go Developer", label: "Go Developer" },
  { value: "Rust Developer", label: "Rust Developer" },
  { value: "React Developer", label: "React Developer" },
  { value: "Angular Developer", label: "Angular Developer" },
  { value: "Vue.js Developer", label: "Vue.js Developer" },
  { value: "Node.js Developer", label: "Node.js Developer" },
  { value: "Express Developer", label: "Express Developer" },
  { value: "Laravel Developer", label: "Laravel Developer" },
  { value: "Django Developer", label: "Django Developer" },
  { value: "Spring Developer", label: "Spring Developer" },
];
